version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    restart: always
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tododb
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
