version: "3.8"

services:

  backend:
    build: ./backend
    restart: always
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tododb
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
